version: "2"

services:
  tor:
    image: goldy/tor-hidden-service:0.3.5.8
    links:
      - hello
    env_file:
      - ./keys/.env

  hello:
    build:
      context: ./packages/hidden-service
      dockerfile: Dockerfile
    hostname: hello
