version: "2"

services:
  tor:
    image: goldy/tor-hidden-service:0.3.5.8
    links:
      - did_onion
    env_file:
      - ./keys/.env

  did_onion:
    build:
      context: ./packages/hidden-service
      dockerfile: Dockerfile
    hostname: did_onion
